"""Static check that every pyqula module-level call the interface layer
makes still exists, and is called with keyword arguments that function
actually accepts.

pysrc/pyqula/ is vendored and refreshed wholesale by
tools/update_pyqula.sh, so a function this repo calls can silently
disappear or change its signature upstream. Nothing catches that until a
user clicks the one button that uses it: tools/smoke_test.py only checks
that a handler is *wired*, and test_handlers.py only runs a handful of
handlers. This is the cheap, whole-codebase net for that class of bug -
it is a pure AST scan plus an `inspect.signature` check, so it costs no
calculation time and covers every handler, including ones no test runs.

It is what would have caught three latent bugs found while auditing the
interface layer for pyqula's bound methods:

  - tbg's "Lowest" DOS mode called dos.dos2d(), which does not exist
    (AttributeError on the tbg DOS tab's *default* mode).
  - hofstader1d's Hofstadter-butterfly sweep called dos.dos1d(), likewise
    nonexistent.
  - hofstader1d/hybridfilm's show_dos called dos.dos0d(h, es=...), whose
    parameter is named "energies".

All three now go through h.get_dos(), pyqula's general DOS entry point -
see INTERFACE_GUIDE.md's "Calling pyqula - prefer the bound methods".

Only module-level calls (`dos.something(...)`) can be checked this way;
bound-method calls (`h.get_dos(...)`) are on a runtime object and are
covered by test_handlers.py running the handlers instead.
"""
import ast
import inspect
import os

import pytest

from interfacetk import qlinterface

QLROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Every pyqula submodule reachable by a bare name in the interface layer:
# qlinterface.py imports them all, and both pysrc/interfacetk/*.py and every
# <mode>.py pull them in through `from .qh_interface import *` / `from
# interfacetk.qh_interface import *`, so its own namespace is the source of
# truth for which bare names resolve to a pyqula module.
PYQULA_MODULES = {
    name: obj for name, obj in vars(qlinterface).items()
    if inspect.ismodule(obj) and getattr(obj, "__name__", "").startswith("pyqula")
}

# quasiperiodic/ and qtwrap/ are pre-existing unwired legacy (PyQt5, stale
# imports, not in the shell's MODES list) - see CLAUDE.md.
SKIP_DIRS = {"quasiperiodic", "qtwrap", "__pycache__"}


def _source_files():
    """Every hand-written interface-layer .py file. Generated interface.py
    files are skipped (they are pure Qt widget construction, regenerated by
    tools/convert_ui.sh, and never call pyqula)."""
    roots = [os.path.join(QLROOT, "pysrc", "interfacetk"),
             os.path.join(QLROOT, "interface-pyqt")]
    for root in roots:
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for fn in sorted(filenames):
                if not fn.endswith(".py") or fn == "interface.py":
                    continue
                yield os.path.join(dirpath, fn)


def _pyqula_calls():
    """Yield (relpath, lineno, module name, attribute, [keyword names]) for
    every `<pyqula module>.<attr>(...)` call in the interface layer."""
    for path in _source_files():
        rel = os.path.relpath(path, QLROOT)
        tree = ast.parse(open(path).read(), filename=path)
        # names rebound locally in this file (assignments, imports, args)
        # would shadow the pyqula module, so drop them rather than checking
        # an attribute against the wrong object
        shadowed = {t.id for node in ast.walk(tree)
                    if isinstance(node, (ast.Assign, ast.For))
                    for t in ast.walk(node.targets[0] if isinstance(node, ast.Assign)
                                      else node.target)
                    if isinstance(t, ast.Name)}
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call): continue
            f = node.func
            if not (isinstance(f, ast.Attribute) and isinstance(f.value, ast.Name)):
                continue
            mod = f.value.id
            if mod not in PYQULA_MODULES or mod in shadowed: continue
            kws = [k.arg for k in node.keywords if k.arg is not None]
            yield (rel, node.lineno, mod, f.attr, kws)


CALLS = list(_pyqula_calls())


def test_scan_found_calls():
    """Guard against the scan silently matching nothing (a refactor of the
    import convention would make every other test here vacuous)."""
    assert len(CALLS) > 20, "the pyqula-call scan found almost nothing - is it still matching?"


@pytest.mark.parametrize("rel,lineno,mod,attr,kws", CALLS,
                         ids=["%s:%s %s.%s" % (r, l, m, a) for r, l, m, a, _ in CALLS])
def test_pyqula_function_exists(rel, lineno, mod, attr, kws):
    obj = getattr(PYQULA_MODULES[mod], attr, None)
    assert obj is not None, (
        "%s:%d calls %s.%s(), which does not exist in the vendored pyqula. "
        "Was it removed/renamed upstream, or is there a general entry point "
        "to call instead (e.g. h.get_dos() rather than dos.dos1d())?"
        % (rel, lineno, mod, attr))


@pytest.mark.parametrize("rel,lineno,mod,attr,kws", [c for c in CALLS if c[4]],
                         ids=["%s:%s %s.%s" % (r, l, m, a) for r, l, m, a, k in CALLS if k])
def test_pyqula_keywords_accepted(rel, lineno, mod, attr, kws):
    obj = getattr(PYQULA_MODULES[mod], attr, None)
    if obj is None: pytest.skip("missing function, reported by the test above")
    try:
        params = inspect.signature(obj).parameters
    except (TypeError, ValueError):
        pytest.skip("no introspectable signature")
    if any(p.kind is inspect.Parameter.VAR_KEYWORD for p in params.values()):
        return # **kwargs: accepts anything, nothing to check
    unknown = [k for k in kws if k not in params]
    assert not unknown, (
        "%s:%d calls %s.%s() with keyword(s) %s it does not accept (its "
        "parameters are %s)" % (rel, lineno, mod, attr, unknown, list(params)))
