#!/usr/bin/env python3

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d

name = sys.argv[1] # name of the file

m = np.genfromtxt(name).transpose()
x,y,z = m[0],m[1],m[2]


def normalize(v):
  v = v-min(v)
  scale = max(abs(min(v)),abs(max(v)))
  return v/scale

x,y,z = normalize(x),normalize(y),normalize(z)

pl = _pv3d.new_plotter()
_pv3d.add_trisurf(pl,x,y,z,cmap="viridis")
pl.view_isometric()
pl.show()
