#!/mnt/extradrive/apps/anaconda3/bin/python

import numpy as np
import matplotlib.pyplot as plt
import sys


import argparse
parser = argparse.ArgumentParser()

parser.add_argument("name")
parser.add_argument("--nx",default=100)
parser.add_argument("--ny",default=100)
args = parser.parse_args()


m = np.genfromtxt(args.name).transpose()

a,b = m[0],m[1]

plt.hist2d(a, b, (int(args.nx), int(args.ny)), cmap=plt.cm.afmhot)
plt.colorbar()
plt.show()
