#!/mnt/extradrive/apps/anaconda3/bin/python

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import sys

# change the font size
import matplotlib
matplotlib.rcParams.update({'font.size': 18})
matplotlib.rcParams['font.family'] = "Bitstream Vera Serif"

write = False # if have to write in a file
remove = False # if have to write in the file to remove
write = True
remove = True

m = np.genfromtxt("POSITIONS.OUT").transpose()
x = m[0]
y = m[1]
z = m[2]
corig = [] # oroginal color
sorig = [] # original size
for iz in z:
  if iz>0.00001: 
    corig.append("lightgreen")
    sorig.append(20)
  else: 
    corig.append("black")
    sorig.append(60)
isred = [False for ix in x] # if selected

plt.ion()

def onpick3(event):
        ind = event.ind
        print('onpick3 scatter:', ind, np.take(x, ind), np.take(y, ind))
        # replot
        try: del red
        except: pass
        for i in ind:
          isred[i] = not isred[i]
          if isred[i]: c = "red"
          else: c = corig[i]
          plt.scatter(x[i],y[i],sorig[i],c)
        plt.title("Red sites will be removed")
        plt.draw() # draw image
        if write: # write in file
          # this is just a workaround, I should do it better in the future
          if remove: namefile = "REMOVE_ATOMS.INFO"
          else: namefile = "SELECTED_ATOMS.INFO"
          fo = open(namefile,"w")
          for (w,i) in zip(isred,range(len(x))):
            if w: fo.write(str(i)+"\n")
          fo.close()
          print("Written selected atoms in "+namefile)
        

fig, ax = plt.subplots()
fig.set_facecolor("white") # white
col = ax.scatter(x, y,sorig, corig, picker=True)
plt.axis("equal")
fig.canvas.mpl_connect('pick_event', onpick3)




plt.show(block=True)
