#!/mnt/extradrive/apps/anaconda3/bin/python

from __future__ import print_function
import numpy as np
import os
import sys


try:
  from mayavi import mlab
except:
  print("Mayavi is not working")
  dirname = os.path.dirname(os.path.realpath(__file__))
  sys.path.append(dirname+"/../pysrc/interpreter")
  import pycommand
  pyc = pycommand.get_python() # get python
  os.system(pyc+" "+dirname+"/qh-structure --input POSITIONS.OUT --color True --colorcol 2&") # use the backup script
  exit()


################################################################################
# Disable the rendering, to get bring up the figure quicker:
mlab.figure("Structure", fgcolor=(0, 0, 0), bgcolor=(1, 1, 1))
figure = mlab.gcf()
mlab.clf()
figure.scene.disable_render = True

# Creates two set of points using mlab.points3d: red point and
# white points



def read_positions():
  """Reads the positions of the system"""
  return np.genfromtxt("POSITIONS.OUT").transpose()


(x1,y1,z1) = read_positions()


xu,yu,zu = [],[],[]  # upper layer
xl,yl,zl = [],[],[]  # lower layer

for (ix,iy,iz) in zip(x1,y1,z1): # loop
  if iz<0.0:
    xu.append(ix)
    yu.append(iy)
    zu.append(iz)
  else:
    xl.append(ix)
    yl.append(iy)
    zl.append(iz)


mlab.points3d(xu, yu, zu, color=(1, 0, 0), scale_factor = .8,
                resolution=10)
mlab.points3d(xl, yl, zl, color=(0, 0, 1), scale_factor = .8,
                resolution=10)


# Every object has been created, we can reenable the rendering.
figure.scene.disable_render = False
################################################################################



mlab.show()
