#!/mnt/extradrive/apps/anaconda3/bin/python

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import sys

fig = plt.figure()
fig.set_facecolor("white")
ax = fig.add_subplot(111, projection='3d')
fig.subplots_adjust(.1,.1,.9,.9)
ax.set_aspect("auto")

names = [sys.argv[i] for i in range(1,len(sys.argv))] # names of the files
for name in names:
  rs = np.genfromtxt(name) # get positions
  
  
  # scatter the central cell
  def scatter(rs,c="red"):
    rs2 = np.array(rs).transpose() # transpose
    ax.scatter(rs2[0],rs2[1],rs2[2],c=c) # scatter the points
  
  scatter(rs)
  
  
  # this is a workaround to fix the same scale
  
  X = rs[:,0]
  Y = rs[:,1]
  Z = rs[:,2]
  
  max_range = np.array([X.max()-X.min(), Y.max()-Y.min(), Z.max()-Z.min()]).max() / 2.0
  
  mid_x = (X.max()+X.min()) * 0.5
  mid_y = (Y.max()+Y.min()) * 0.5
  mid_z = (Z.max()+Z.min()) * 0.5
  ax.set_xlim(mid_x - max_range, mid_x + max_range)
  ax.set_ylim(mid_y - max_range, mid_y + max_range)
  ax.set_zlim(mid_z - max_range, mid_z + max_range)
  ###################################
  # end of the workaround
  





plt.show()



