#!/usr/bin/env python3

lattice_color = "yellow"
ldos_color = "green"

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d

name = sys.argv[1] # name of the file
m = np.genfromtxt(name).transpose()

xyz = np.array([m[0],m[1],m[0]*0.]) # positions (flat, z=0)
rs = xyz.transpose()

pl = _pv3d.new_plotter()
_pv3d.add_atoms(pl,xyz,color=lattice_color)
_pv3d.add_bonds(pl,rs,rs,dmin=1e-6,dmax=1.005,color=lattice_color,radius=0.1)
# a halo around each atom, not add_scaled_points: that renders in
# screen pixels, so it would drift out of registration with the
# (correctly world-sized) atoms above as the camera zooms - see
# add_atoms_colored's docstring
nn = _pv3d.nearest_neighbor_distance(xyz.transpose())
_pv3d.add_atoms(pl,xyz,color=ldos_color,radius=nn/1.5,opacity=0.5)
pl.show()
