#!/home/joselado/apps/anaconda3/bin/python

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import sys



import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--input",default="POSITIONS.OUT",
        help='Input file')
parser.add_argument("--color",default="False",help='Color')
parser.add_argument("--size",default="1.",help='Size')

args = parser.parse_args() # get the arguments



# change the font size
import matplotlib
matplotlib.rcParams.update({'font.size': 18})
matplotlib.rcParams['font.family'] = "Bitstream Vera Serif"

m = np.genfromtxt(args.input).transpose()
x = m[0]
y = m[1]
z = m[2]
sorig = x*0. + 500/np.sqrt(len(x)) # original size
sorig = sorig*float(args.size)

plt.ion()

fig, ax = plt.subplots()
currentfig = plt.gcf()
currentfig.canvas.setWindowTitle('Structure')
plt.title("Number of atoms "+str(len(x)))
fig.set_facecolor("white") # white
if args.color=="True":
  col = ax.scatter(x, y,sorig, c=z, cmap="rainbow")
else:
  col = ax.scatter(x, y,sorig, c="black", picker=True)
plt.axis("equal")




plt.show(block=True)
