#!/usr/bin/env python3

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt

import os, sys
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
import plotstyle
plotstyle.apply()

path = os.path.dirname(os.path.realpath(__file__)) # current path
path += "/../pysrc"
sys.path.append(path) # add library
from interfacetk import plotpyqt

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--input",default="LATTICEISING_FRAMES",help='Input folder')
args = parser.parse_args() # get the arguments

folder = args.input+"/" # folder with all the snapshots

names = open(folder+"LATTICEISING_FRAMES.TXT").readlines() # read the files
names = [name.replace("\n","") for name in names] # remove newline
steps = [int(name.split("_")[2]) for name in names] # trial step of each frame
frames = [np.genfromtxt(folder+name).transpose() for name in names] # load every snapshot up front

es = None
if os.path.isfile("ENERGY.OUT"):
  es = np.genfromtxt("ENERGY.OUT").transpose() # iteration, energy

ms = None
if os.path.isfile("MAGNETIZATION.OUT"):
  ms = np.genfromtxt("MAGNETIZATION.OUT").transpose() # iteration, total magnetization


def plot(main):
  """Plotting function"""
  fig = plt.gcf()
  fig.set_facecolor(plotstyle.BACKGROUND)
  fig.canvas.setWindowTitle("Ising model relaxation")
  ii = int(main.get_slider("Step"))
  step = steps[ii]
  m = frames[ii]
  x,y,z = m[0],m[1],m[2] # x, y, spin
  ax = fig.add_subplot(121) if es is not None else fig.add_subplot(111)
  size = np.power(main.get_slider("Size"),4)
  ax.scatter(x,y,s=100*size,c=z,edgecolor="none",cmap="bwr",vmin=-1,vmax=1)
  ax.axis("equal")
  ax.set_xticks([]) ; ax.set_yticks([])
  ax.set_title("Step %d/%d"%(step,steps[-1]))
  if es is not None:
    axe = fig.add_subplot(122)
    axe.plot(es[0],es[1],color=plotstyle.PRIMARY)
    marker = step if step<=es[0][-1] else es[0][-1]
    axe.axvline(marker,color=plotstyle.SECONDARY,linewidth=2.0)
    axe.set_xlabel("Iteration")
    axe.set_ylabel("Energy",color=plotstyle.PRIMARY)
    if ms is not None: # total magnetization on a shared twin axis
      axm = axe.twinx()
      axm.plot(ms[0],ms[1],color=plotstyle.SECONDARY,alpha=0.6)
      axm.set_ylabel("Magnetization",color=plotstyle.SECONDARY)
  return fig


app,main = plotpyqt.get_interface(plot)
main.add_slider(label="Step",vs=range(len(frames)),v0=0)
main.add_slider(label="Size",vs=np.linspace(0.,2,100),v0=0.8)
main.setWindowTitle("Ising model relaxation")

main.plot()
main.show()
sys.exit(app.exec_())
