#!/usr/bin/env python3

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt

import os, sys
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
import plotstyle
plotstyle.apply()

fig = plt.figure()
fig.set_facecolor(plotstyle.BACKGROUND)

m = np.genfromtxt("CORRELATOR.OUT").transpose()
x = m[0] # neighbor distance
y = m[1] # density-density correlator

plt.plot(x,y,color=plotstyle.PRIMARY,marker="o",linewidth=2.0)
plt.axhline(0.0,color=plotstyle.SECONDARY,linewidth=1.0)
plt.xlabel("Neighbor distance")
plt.ylabel("Density-density correlator")

plt.show()
