#!/usr/bin/env python3

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d


def read_positions():
  """Reads the positions of the system"""
  return np.genfromtxt("POSITIONS.OUT").transpose()


(x,y,z) = read_positions()

pl = _pv3d.new_plotter()
_pv3d.add_atoms(pl,(x,y,z),color="magenta")
pl.show()
