#!/usr/bin/env python3


import numpy as np
import matplotlib.pyplot as plt
import sys



fig = plt.figure()

name = sys.argv[1]

fig.set_facecolor("white")
m = np.genfromtxt(name).transpose()

for i in range(len(m)-1):
  plt.plot(m[0],m[i+1],marker="o")

plt.show()
