#!/usr/bin/env python3

# this script read mean_field.in and calculates the magnetism in the
# different sites
# it assumes that each position has spin up and down (2*i,2*i+1)

lattice_color = (0.8,.8,0.6) # color of the lattice

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--input",default="MAGNETISM.OUT",
        help='Input file')
parser.add_argument("--xwindow",default="None",
        help='xwindow')
parser.add_argument("--ywindow",default="None",
        help='ywindow')
parser.add_argument("--zwindow",default="None",
        help='zwindow')
parser.add_argument("--bonds",default="True",
        help='Use bonds')
parser.add_argument("--magnetization",default="True",
        help='xwindow')
parser.add_argument("--bondl",default="1.1",
        help='xwindow')

args = parser.parse_args() # get the arguments

mag_factor = 1.5


def read_data():
  """Reads the positions of the system"""
  m = np.genfromtxt(args.input)
  if args.xwindow!="None":
      xw = float(args.xwindow) # x window
      m = m[np.abs(m[:,0])<xw,:]
  if args.ywindow!="None":
      xw = float(args.ywindow) # x window
      m = m[np.abs(m[:,1])<xw,:]
  if args.zwindow!="None":
      xw = float(args.zwindow) # x window
      m = m[np.abs(m[:,2])<xw,:]
  return m


def get_mag():
  """ Get the magnetization """
  m = read_data().T
  return (range(len(m[0])),np.array([m[3],m[4],m[5]]))


def read_positions():
  m = read_data()
  return m[:,0:3]


get_magnetization = get_mag # use a particular function
get_positions = read_positions # use a particular function

xyz = get_positions().transpose()


def scale_mag(mag,threshold=1e-9):
  """ Scales the magnetism if bigger than a certain threhold"""
  mmag = mag.transpose()
  mm = np.array([im.dot(im) for im in mmag]) # norms square
  mm = np.sqrt(mm) # vector with norms
  if np.max(mm)<threshold:  # if small do nothing
    return mag
  else:
    mag = mag/np.max(mm) # set maaximum norm to 1
    m2 = np.power(mm,3./4.)
    m2 /= np.max(m2) # list of norms renormalized
    mag = mag/m2 # renormalized length (for visualization purposes)
    return mag


pl = _pv3d.new_plotter("Magnetism")


def create_lattice(xyz):
  """ Creates a lattice using xyz coordinates"""
  _pv3d.add_atoms(pl,xyz,color=lattice_color,radius=0.55)


def create_arrow(r,v,fac=2):
   """Create an arrow"""
   pl.add_arrows(np.array([r]),np.array([v]),mag=fac,color="red")


def plot_magnetization(xyz,mag,dr=np.array([0.,0.,0.])):
  """ PLots the magnetization with arrows"""
  global mag_factor
  mag = scale_mag(mag)*mag_factor*0.8
  for i in range(len(xyz[0])):
    r = np.array([xyz[0][i],xyz[1][i],xyz[2][i]])
    v = np.array([mag[0][i],mag[1][i],mag[2][i]])
    size = v.dot(v) # size of the arrow
    create_arrow(r+dr,v,fac=size)


def create_bonds(rs1,rs2):
  """ Creates the bonds of the crystal """
  bondl = float(args.bondl)
  _pv3d.add_bonds(pl,rs1,rs2,dmin=np.sqrt(0.1),dmax=np.sqrt(bondl),
                   color=lattice_color,radius=0.1)


create_lattice(xyz)    # plot the atoms

(ind,mag) = get_magnetization() # get the orbital index and magnetizations
if args.magnetization=="True":
  plot_magnetization(xyz,mag)   # plot the magnetization as cylinders

############################
# Create bonds ############
############################
rs = xyz.transpose()
if args.bonds=="True":
  create_bonds(rs,rs)


pl.show()
