#!/usr/bin/env python3

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--input",default="MAGNETISM.OUT",
        help='Input file with the magnetization')
parser.add_argument("--bonds",default="True",
        help='Plot the bonds')
parser.add_argument("--arrows",default="True",
        help='Plot the arrows')
parser.add_argument("--arrowsize",default="1.0",
        help='Size of the arrows')
parser.add_argument("--bondsize",default="1.0",
        help='Size of the bonds')
parser.add_argument("--sitesize",default="1.0",
        help='Size of the sites')

args = parser.parse_args() # get the arguments

lattice_color = "cyan"
mag_factor = float(args.arrowsize)*2.0


class crystal:
  dimensionality = 0
  a1 = np.array([0.,0.,0.])
  a2 = np.array([0.,0.,0.])
  a3 = np.array([0.,0.,0.])


def get_mag():
  """ Get the magnetization """
  return np.genfromtxt(args.input).T[3:6]


def read_positions():
  """Reads the positions of the system"""
  return np.genfromtxt(args.input).T[0:3]


def get_lattice(crys):
  """Get the lattice vectors"""
  f = "LATTICE.OUT"
  if os.path.isfile(f):
    if  len(open(f,"r").readlines()) == 1:  # one dimensional
      crys.dimensionality = 1
      a1 = np.genfromtxt("LATTICE.OUT")
      try:
        a1[0]==1
      except:
        a1 = np.array([a1,0.,0.])
      crys.a1 = a1  # store in class
      return a1
    elif len(open(f,"r").readlines()) == 2:  # two dimensional
      crys.dimensionality = 2
      a1 = np.genfromtxt("LATTICE.OUT")[0]
      a2 = np.genfromtxt("LATTICE.OUT")[1]
      crys.a1, crys.a2 = a1, a2
    else:
      raise
  else:
    crys.dimensionality = 0


get_magnetization = get_mag # use a particular function
get_positions = read_positions # use a particular function

xyz = get_positions()


def scale_mag(mag,threshold=0.001):
  """ Scales the magnetism if bigger than a certain threhold"""
  mmag = mag.transpose()
  mm = np.array([im.dot(im) for im in mmag]) # norms square
  mm = np.sqrt(mm) # vector with norms
  if max(mm)<threshold:  # if small do nothing
    return mag
  else:
    return mag/max(mm)


pl = _pv3d.new_plotter("Magnetism")


def create_atom(P,rad=0.55):
   """
     Draws an atom (sphere) at point P
     P: array-like object
   """
   rad = rad*float(args.sitesize)
   _pv3d.add_atoms(pl,P,color=lattice_color,radius=rad)


def create_lattice(xyz,dr=[0.,0.,0.]):
  """ Creates a lattice using xyz coordinates"""
  dr = np.array(dr)
  xyz2 = (xyz.transpose() + dr).transpose()
  create_atom(xyz2)


def create_arrow(r,v,fac=2):
   """
     Draws an arrow starting at point r and with direction v
     The size is tricky, and is controlled by the parameter fac...
     ...good luck!
     r & v: arra-like objects
   """
   pl.add_arrows(np.array([r]),np.array([v]),mag=fac,color="red")


def plot_magnetization(xyz,mag,dr=np.array([0.,0.,0.])):
  """ PLots the magnetization with arrows"""
  global mag_factor
  mag = scale_mag(mag)*mag_factor*0.8
  for i in range(len(xyz[0])):
    r = np.array([xyz[0][i],xyz[1][i],xyz[2][i]])
    v = np.array([mag[0][i],mag[1][i],mag[2][i]])
    size = v.dot(v) # size of the arrow
    create_arrow(r+dr,v,fac=size)


def create_bonds(rs1,rs2):
  """ Creates the bonds of the crystal """
  _pv3d.add_bonds(pl,rs1,rs2,dmin=np.sqrt(0.1),dmax=np.sqrt(1.1),
                   color=lattice_color,radius=0.1*float(args.bondsize))


crys = crystal() # create a crystal class

ncells = 0 # number of cells
try:
  ncells = int(sys.argv[1]) # number of cells
except (IndexError,ValueError):
  ncells = 0 # number of cells
  print("Ploting only one cell")

if ncells>0:
  try: get_lattice(crys) # get lattice vectors
  except Exception as e: print("Could not read LATTICE.OUT:",e)


# plot the atoms
##############################################
das = [] # number of displacements
if crys.dimensionality == 0:
  create_lattice(xyz)    # plot the atoms
if crys.dimensionality == 1:
  for i in range(-ncells,ncells+1):
    create_lattice(xyz,dr=crys.a1*i)    # plot the atoms
    das.append([i,0,0])
if crys.dimensionality == 2:
  for i in range(-ncells,ncells+1):
    for j in range(-ncells,ncells+1):
      create_lattice(xyz,dr=crys.a1*i + crys.a2*j)    # plot the atoms
      das.append([i,j,0])
##############################################


# Plot magnetization
##############################################
if args.arrows=="True":
    mag = get_magnetization() # get the orbital index and magnetizations
    plot_magnetization(xyz,mag)   # plot the magnetization as cylinders
    for da in das: # and loop over replicas
      plot_magnetization(xyz,mag,dr=crys.a1*da[0] + crys.a2*da[1])
##############################################


############################
# Create bonds ############
############################
rs = xyz.transpose()
if args.bonds=="True":
  create_bonds(rs,rs)
  for da1 in das:
    for da2 in das:
      dr1 = crys.a1*da1[0] + crys.a2*da1[1] + crys.a3*da1[2]
      dr2 = crys.a1*da2[0] + crys.a2*da2[1] + crys.a3*da2[2]
      rs1 = [ri + dr1 for ri in rs]
      rs2 = [ri + dr2 for ri in rs]
      create_bonds(rs1,rs2)


pl.show()
