#!/usr/bin/env python3

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d

name = "BERRY_CURVATURE.OUT" # Berry curvature file

m = np.genfromtxt(name).transpose()
x,y,z = m[0],m[1],m[2]


def sc(v):
  v = v-min(v)
  scale = max(abs(min(v)),abs(max(v)))
  return v/scale

x,y,z = sc(x),sc(y),sc(z)

try:
  s = float(sys.argv[2])
except (IndexError,ValueError):
  s = 1.0

z = z/s

pl = _pv3d.new_plotter()
_pv3d.add_trisurf(pl,x,y,z,cmap="viridis")
pl.add_title("C = "+open("CHERN.OUT").read()+" ")
pl.view_isometric()
pl.show()
