#!/usr/bin/env python3

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d

names = sys.argv[1:] # names of the files

pl = _pv3d.new_plotter()
for name in names:
  m = np.genfromtxt(name).transpose()
  x,y,z = m[0],m[1],m[2]
  _pv3d.add_trisurf(pl,x,y,z,cmap="viridis")

pl.view_isometric()
pl.show()
