#!/usr/bin/env python3

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d


def read_positions():
  """Reads the positions of the system"""
  return np.genfromtxt("POSITIONS.OUT").transpose()


(x1,y1,z1) = read_positions()
points = np.array([x1,y1,z1]).T

pl = _pv3d.new_plotter()
pl.add_points(points,render_points_as_spheres=True,point_size=40,color="blue")


def picker_callback(point_id):
    """ Called when the user clicks on a point"""
    x,y,z = x1[point_id],y1[point_id],z1[point_id]
    print(point_id,x,y,z)
    pl.add_text("Selected atom "+str(point_id)+" ",position="upper_edge",name="pick_title")


_pv3d.enable_point_picking(pl,points,picker_callback)
pl.show()
