#!/usr/bin/env python3

import os
import sys
import numpy as np
import pyvista as pv

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d


def read_positions():
  """Reads the positions of the system"""
  return np.genfromtxt("POSITIONS.OUT").transpose()


(x1,y1,z1) = read_positions()
points = np.array([x1,y1,z1]).T
removed = [False for x in x1] # none removed

pl = _pv3d.new_plotter()
namefile = "REMOVE_ATOMS.INFO"


def write_selection():
    with open(namefile,"w") as fo:
        for i,r in enumerate(removed):
            if r: fo.write(str(i)+"\n")
    print("Written selected atoms in "+namefile)


def redraw():
    """Blue for kept atoms, red for atoms marked for removal"""
    cloud = pv.PolyData(points)
    cloud["removed"] = np.array([1 if r else 0 for r in removed])
    pl.add_mesh(cloud,render_points_as_spheres=True,point_size=40,
                scalars="removed",cmap=["blue","red"],clim=[0,1],
                show_scalar_bar=False,name="atoms")


redraw()


def picker_callback(point_id):
    """ Called when the user clicks on a point: toggles its removal"""
    removed[point_id] = not removed[point_id]
    redraw()
    pl.add_text("Selected atom "+str(point_id)+" ",position="upper_edge",name="pick_title")
    write_selection()


_pv3d.enable_point_picking(pl,points,picker_callback)
pl.show()
