#!/usr/bin/env python3

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d


def read_positions():
  """Reads the positions of the system"""
  return np.genfromtxt("POSITIONS.OUT").transpose()


(x1,y1,z1) = read_positions()

ca = (z1-np.min(z1))/(np.max(z1)-np.min(z1)+1e-3) # scaled height, used for color

pl = _pv3d.new_plotter("Structure")
_pv3d.add_scaled_points(pl,(x1,y1,z1),ca,cmap="cool",point_size=25,opacity=1.0)
pl.show()
