#!/usr/bin/env python3

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import sys

import matplotlib
import os, sys
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
import plotstyle
plotstyle.apply()

fig = plt.figure()

fig.set_facecolor("white") # white

name = sys.argv[1] # name of the file

m = np.genfromtxt(name).transpose() # read file
x = m[0] # x position
y = m[1] # y position
z = m[2] # z position

scale = np.abs(z)/np.max(np.abs(z))*500
zsign = np.sign(z) # sign

plt.title(str(len(x))+" atoms")
plt.scatter(x,y,color=plotstyle.PRIMARY,s=1)
#plt.scatter(x,y,s=60,c=scale,edgecolor="none",cmap=plt.get_cmap("inferno"))
plt.scatter(x,y,s=60,c=scale,edgecolor="none")
plt.xticks([])
plt.yticks([])

plt.axis("equal")
plt.savefig(name+".png") # save the image
