#!/usr/bin/env python3

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import sys


import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--input",default="POSITIONS.OUT",
        help='Input file')
parser.add_argument("--bondl",default="1.2",
        help='Distance between sites')

args = parser.parse_args() # get the arguments






import matplotlib
import os, sys
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
import plotstyle
plotstyle.apply()
import _cell

fig = plt.figure()
plt.gcf().canvas.setWindowTitle('Structure')

fig.set_facecolor(plotstyle.BACKGROUND) # white

name = args.input

m = np.genfromtxt(name).transpose() # read file
x = m[0] # x position
y = m[1] # y position
z = m[2] # z position



size = 500./np.sqrt(len(z))
#size = 100

plt.title(str(len(x))+" atoms")
plt.scatter(x,y,color=plotstyle.PRIMARY,s=size)
plt.xticks([])
plt.yticks([])

bondl = float(args.bondl)
for i in range(len(x)):
  for j in range(i,len(x)):
    dd = (x[i] -x[j])**2 + (y[i] -y[j])**2
    if 0.8<dd<bondl:
      plt.plot([x[i],x[j]],[y[i],y[j]],c=plotstyle.PRIMARY)

cell = _cell.read_cell()
if cell is not None:
  dim, vecs = cell
  if dim==1:
    span = (np.max(y)-np.min(y)+1)*0.05 or 0.3
    edges = _cell.cell_1d_ticks(vecs,span)
  else:
    edges = _cell.cell_edges(dim,vecs)
  for (p0,p1) in edges:
    plt.plot([p0[0],p1[0]],[p0[1],p1[1]],color=plotstyle.ACCENT,
              linestyle="--",linewidth=1.8,zorder=10)

plt.axis("equal")
plt.show()
