#!/usr/bin/env python3

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d
import _cell

lattice_color = tuple(np.random.random(3))


def read_positions():
  """Reads the positions of the system"""
  return np.genfromtxt("POSITIONS.OUT")


xyz = read_positions().transpose() # (3,n)
rs = xyz.transpose() # (n,3)

pl = _pv3d.new_plotter("Structure")
_pv3d.add_atoms(pl,xyz,color=lattice_color)

if len(rs)<250:
  _pv3d.add_bonds(pl,rs,rs,dmin=0.8,dmax=1.2,color=lattice_color,radius=0.1)

cell = _cell.read_cell()
if cell is not None:
  dim, vecs = cell
  nn = _pv3d.nearest_neighbor_distance(rs)
  if dim==1: edges = _cell.cell_1d_ticks(vecs,nn)
  else: edges = _cell.cell_edges(dim,vecs)
  _pv3d.add_cell(pl,edges,radius=nn/10.)

pl.show()
