#!/usr/bin/env python3

# this script read mean_field.in and calculates the magnetism in the
# different sites
# it assumes that each position has spin up and down (2*i,2*i+1)

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d

name = sys.argv[1] # name of the file

m = np.genfromtxt(name).transpose()

if len(m)==6:
    X,Y,Z,Vx,Vy,Vz = m
elif len(m)==4:
    X,Y = m[0],m[1]
    Z = m[0]*0.0
    Vx,Vy = m[2],m[3]
    Vz = m[0]*0.0
else:
    print("Number of columns not recognised")
    raise SystemExit(1)

V = np.max(np.sqrt(Vx*Vx+Vy*Vy+Vz*Vz)) # normalize
Vx,Vy,Vz = Vx/V,Vy/V,Vz/V

pl = _pv3d.new_plotter()
_pv3d.add_arrows(pl,(X,Y,Z),(Vx,Vy,Vz),color="red",mag=1.0)
pl.show()
