#!/usr/bin/env python3

import os
import sys
import numpy as np

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0,dirname)
import _pv3d

name = sys.argv[1]
m = np.genfromtxt(name).transpose() # read file

x,y,s = m[0],m[1],m[2]
part = np.sum(s*s)

print("Participation Ratio = ",part)

s = s/np.max(s)  # normalize
zeros = y*0.

pl = _pv3d.new_plotter()
_pv3d.add_atoms(pl,(x,y,zeros),color="black")
_pv3d.add_scaled_points(pl,(x,y,zeros),s,color="red",point_size=25,opacity=0.7)
pl.show()
