#!/mnt/extradrive/apps/anaconda3/bin/python


import mayavi.mlab as mlab
import numpy as np
import sys

#name = sys.argv[1] # name of the file


m = np.genfromtxt("POSITIONS.OUT").transpose()
x = m[0]
y = m[1]
z = np.genfromtxt("LDOS.OUT")


z = z -min(z)
scale_z = max(abs(min(z)),abs(max(z)))
z = z/scale_z

from mayavi import mlab
mlab.figure(1, fgcolor=(0, 0, 0), bgcolor=(1, 1, 1))

# Visualize the points
pts = mlab.points3d(x, y, z, z, scale_mode='none', scale_factor=0.0)

# Create and visualize the mesh
mesh = mlab.pipeline.delaunay2d(pts)
surf = mlab.pipeline.surface(mesh)

mlab.view(47, 57, 8.2, (0.1, 0.15, 0.14))
mlab.show()
