#!/mnt/extradrive/apps/anaconda3/bin/python

import numpy as np
import numpy 
from mayavi.mlab import *

figure(1, fgcolor=(0, 0, 0), bgcolor=(1, 1, 1))





def lorentz(centers=[[0.],[0.]], heights=[10.0]):
    """ Creates a set of lorentzian at that position and with a height"""
    if len(heights)<len(centers):
      heights = [10. for i in centers]
    fac = 5.0 # factor to mix the gaussians
    xs = centers[0] # get x coordinates
    ys = centers[1] # get y coordinates
    def wave(x,y):
      z = 0.
      for (ix,iy,h) in zip(xs,ys,heights):
        r = ((x-ix)**2+(y-iy)**2)*fac # renormalized gaussian       
        z += h*np.exp(-(r))
      return z+1.0
    dxy = (max(xs) - min(xs))/200
    [x, y] = numpy.mgrid[-1+min(xs):1.+max(xs):dxy,
                               -1+min(ys):1+max(ys):dxy]
    z = wave(x,y)
    return mesh(x, y, z, colormap="bone")

def read_ldos():
  """ Read the data"""
  m = np.genfromtxt("LDOS.OUT").transpose() 
  return [m[0],m[1]],m[2]
  

# get the centers of the balls
centers,heights = read_ldos()
heights = 4*heights/max(heights)

lorentzs = lorentz(centers=centers,heights=heights)

show()
