#!/mnt/extradrive/apps/anaconda3/bin/python

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import sys

# change the font size
import matplotlib
matplotlib.rcParams.update({'font.size': 18})


### script for ploting BANDS.OUT of tb90 ###


from os import system as sh


def scatter_color():
  """ Plots the bandstructure from BANDS.OUT"""
  fig = plt.figure()    
  fig.subplots_adjust(0.2,0.2)
  
  # the color map
  import numpy as np
  cdict={'red': ((0., 0, 0),(0.6,0.0,0.0),(1, 1.0, 1.0)), 'green': ((0., 0.0, 0.0),(0.4,1.0,1.0),(0.6,1.0,1.0),(1, 0.0, 0.0)), 'blue': ((0., 1.0, 1.0),(0.4,0.0,0.0), (1, 0.0, 0.0))}
  import matplotlib
  my_cmap = matplotlib.colors.LinearSegmentedColormap('my_colormap',cdict,256)
  
  
  
  
  
  
  name = sys.argv[1] 
  m = np.genfromtxt(name).transpose()
  
  
  
  x = m[0] # default x axis
  y = m[1] # default x axis
  col = plt.scatter(x,y,c=color,cmap=my_cmap, color ="black",edgecolors='none')
  plt.xlim([min(x),max(x)])   # x axis range
  plt.ylim([min(y),max(y)])   # y axis range
 

scatter_color()
plt.show() 
