#!/mnt/extradrive/apps/anaconda3/bin/python

### script for plot maximun values of CHI_R.OUT and CHI_I.OUT of tb90 ###

import numpy as np
import pylab as plt

# maximun in absolute value
def relative_max(x,y):
  """Return an array with the relative maxima"""
  ya = np.abs(y)
  xo = []
  yo = []
  io = 0
  for i in range(1,len(y)-1):
    if ya[i-1]<ya[i]>ya[i+1]:
      if x[i]>0:
        xo.append(io)
        yo.append(x[i])
        io +=1
  xo = np.array(xo)
  yo = np.array(yo)
  fo = open("CHI_POLES.OUT","w")
  fo.write("# index of the pole,   Energy of the pole\n")
  for (ix,iy) in zip(xo,yo):
    fo.write(str(ix)+"    "+str(iy)+"\n")
  fo.close()
  return (xo,yo)



# plot the maximun values
def plot_max(sp,namefile):
  m = np.genfromtxt(namefile).transpose()
  # and plot
  (ind,ene) = relative_max(m[0],m[1])
  sp.plot(ind, ene, marker = 'o', label = "Real(Chi)" )
  



## setup the plots
pi = plt.subplot(1,1,1)

## real part
#plot_max(pr,"CHI_RPA_R_TRACE.OUT")
plot_max(pi,"CHI_RPA_I_TRACE.OUT")



plt.savefig("CHI_RI.png")

plt.show()
