#!/mnt/extradrive/apps/anaconda3/bin/python


from __future__ import print_function
import pylab as py
import sys
import numpy as np

fig = py.figure()
fig.set_facecolor("white")

name = sys.argv[1]  # name of the file

m = py.genfromtxt(name).transpose()
x = m[0]
y = m[1]
z = m[2]

# get dimensions assuming uniform grid

  
ny = (y.max()-y.min())/abs(y[1]-y[0])
ny = int(round(ny)) + 1
nx = len(z)/ny


nx = int(nx)
ny = int(ny)


print("Detected",nx,ny,"grid")

Z = np.abs(z).reshape(nx,ny) # makes a (Zy,Zx) matrix out of z
Z = z.reshape(nx,ny) # makes a (Zy,Zx) matrix out of z
T = Z.T              # transposes the matrix (Zx,Zy)

# now interpolate to get a smooth mesh
from scipy.interpolate import interp2d
x = np.linspace(0.,1.,nx)
y = np.linspace(0.,1.,ny)
xx, yy = np.meshgrid(x, y)
f = interp2d(x, y, T, kind='linear')

# 
x = np.linspace(0.,1.,1000)
y = np.linspace(0.,1.,1000)

z_inter = f(x,y)

# now plot the data
py.imshow(-z_inter, aspect='auto', origin='lower',cmap = py.get_cmap("spectral"), extent = ( x.min(), x.max(), y.min(), y.max()),interpolation='nearest')
py.xticks([])
py.yticks([])

if "save" in sys.argv: py.savefig("MAP.png")
if not "noshow" in sys.argv: # not show
  py.show()
