#!/mnt/extradrive/apps/anaconda3/bin/python

import pylab as py
import sys
import matplotlib

matplotlib.rcParams.update({'font.size': 18})

fig = py.figure()
fig.set_facecolor("white") # white face

m = py.genfromtxt("BERRY_CURVATURE.OUT").transpose() # get the curvature

ind = [float(i) for i in range(len(m[0]))] # create the indices
ind = py.array(ind)/len(ind) # normalice to 1

py.plot(ind,m[2],marker="o",color="red")

# add the lines in the bandstructure
if "label" in sys.argv:
  ll = open("BANDLINES.OUT","r").readlines()
  ik = [] 
  names = [] 
  for l in ll:
    l = l.split()
    ik.append(float(l[0])/len(ind))
    names.append("$"+l[1]+"$")
  py.xticks(ik,names)

py.ylabel("Berry curvature")


py.show()

