#!/mnt/extradrive/apps/anaconda3/bin/python


import numpy as np
import pylab as py
import sys



fig = py.figure()


nfiles = len(sys.argv) -1 # number of files to plot

for i in range(nfiles):
  name = sys.argv[1+i] # name of the file
  m = np.genfromtxt(name).transpose()
  x = m[0]
  y = m[1]
  fig.set_facecolor("white")
#  py.plot(x,y,linewidth=3.0,label=name,color="black",marker="o")
  py.plot(x,y,label=name,color="black",marker="o")
  py.xlim([min(x),max(x)])
#py.legend()
py.show()

