#!/mnt/extradrive/apps/anaconda3/bin/python

import numpy as np
import pylab as pl

### script for ploting DOS.OUT of tb90 ###


# change the font size
import matplotlib
matplotlib.rcParams.update({'font.size': 18})
matplotlib.rcParams['font.family'] = "Bitstream Vera Serif"

# cretae figure and adjust subplot
fig = pl.figure(1)
fig.subplots_adjust(0.2,0.2)

m = np.genfromtxt("DOS.OUT").transpose()
num_dos = len(m) - 1
e = m[0]
d = m[1]

if num_dos>1:
  for i in range(num_dos):
    dos = m[i+1]
    splot = pl.subplot(num_dos/2,2,i+1)
    splot.plot(e,dos,color="black")
    splot.set_xlim([min(e),max(e)])
    splot.set_xlabel("Energy")
    splot.set_ylabel("DOS")
else:  # pot only one DOS
  dos = m[1]
  splot = pl.subplot(1,1,1)
  splot.plot(e,dos,color="black")
  splot.set_xlim([min(e),max(e)])
  splot.set_xlabel("$E/t$")
  splot.set_ylabel("$DOS$")
  # fill until the fermi level
  efill = []
  dfill = []
  for (ie,idos) in zip(e,dos): # get only negative energies
    if ie < 0.:
      efill.append(ie) 
      dfill.append(idos) 
  splot.fill_between(efill,0,dfill,color="yellow")
  splot.set_ylim([0.,max(dos)])  
  splot.set_xlim([min(e)-0.01,max(e)+0.01])  

fig.set_facecolor('white')




pl.show()
