#!/mnt/extradrive/apps/anaconda3/bin/python

import numpy as np
import numpy 
from mayavi.mlab import *

figure(1, fgcolor=(0, 0, 0), bgcolor=(1, 1, 1))



def lorentz(centers=[[0.,0.,0.]], heights=[10.0]):
    """ Creates a set of lorentzian at that position and with a height"""
    if len(heights)<len(centers):
      heights = [10. for i in centers]
    fac = 5.0 # factor to mix the gaussians
    def wave(x,y):
      z = 0.
      for (c,h) in zip(centers,heights):
        r = ((x-c[0])**2+(y-c[1])**2)*fac # renormalized gaussian       
        z += h*np.exp(-(r))-c[2]
      return z+1.0
    xs = [c[0] for c in centers] # get x coordinates
    ys = [c[1] for c in centers] # get y coordinates
    dxy = (max(xs) - min(xs))/200
    [x, y] = numpy.mgrid[-1+min(xs):1.+max(xs):dxy,
                               -1+min(ys):1+max(ys):dxy]
    z = wave(x,y)
    return mesh(x, y, z, colormap="bone")

#centers = np.arange(0.,10.,2.)


# get the centers of the balls
m = np.genfromtxt("LDOS.OUT").transpose()
centers = [[m[0,i],m[1,i],0.] for i in range(len(m[0]))]
heights = m[2]
#heights = read_density()
heights = 4*heights/max(heights)
#heights = np.sqrt(heights)
#balls = [ball(center=c) for c in centers]



lorentzs = lorentz(centers=centers,heights=heights)

show()
