# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 659)
        MainWindow.setMinimumSize(QtCore.QSize(950, 659))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_38 = QtWidgets.QLabel(self.tab_11)
        self.label_38.setObjectName("label_38")
        self.gridLayout_10.addWidget(self.label_38, 4, 0, 1, 1)
        self.Bz_2 = QtWidgets.QLineEdit(self.tab_11)
        self.Bz_2.setObjectName("Bz_2")
        self.gridLayout_10.addWidget(self.Bz_2, 4, 1, 1, 1)
        self.mAF_2 = QtWidgets.QLineEdit(self.tab_11)
        self.mAF_2.setObjectName("mAF_2")
        self.gridLayout_10.addWidget(self.mAF_2, 10, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_11)
        self.label_42.setObjectName("label_42")
        self.gridLayout_10.addWidget(self.label_42, 11, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_11)
        self.label_36.setObjectName("label_36")
        self.gridLayout_10.addWidget(self.label_36, 2, 0, 1, 1)
        self.Bx_2 = QtWidgets.QLineEdit(self.tab_11)
        self.Bx_2.setObjectName("Bx_2")
        self.gridLayout_10.addWidget(self.Bx_2, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_11)
        self.label_22.setObjectName("label_22")
        self.gridLayout_10.addWidget(self.label_22, 9, 0, 1, 1)
        self.fermi_2 = QtWidgets.QLineEdit(self.tab_11)
        self.fermi_2.setEnabled(True)
        self.fermi_2.setObjectName("fermi_2")
        self.gridLayout_10.addWidget(self.fermi_2, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_11)
        self.label_34.setObjectName("label_34")
        self.gridLayout_10.addWidget(self.label_34, 3, 0, 1, 1)
        self.mAB_2 = QtWidgets.QLineEdit(self.tab_11)
        self.mAB_2.setObjectName("mAB_2")
        self.gridLayout_10.addWidget(self.mAB_2, 9, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_11)
        self.label_41.setObjectName("label_41")
        self.gridLayout_10.addWidget(self.label_41, 7, 0, 1, 1)
        self.haldane_2 = QtWidgets.QLineEdit(self.tab_11)
        self.haldane_2.setObjectName("haldane_2")
        self.gridLayout_10.addWidget(self.haldane_2, 7, 1, 1, 1)
        self.antihaldane_2 = QtWidgets.QLineEdit(self.tab_11)
        self.antihaldane_2.setObjectName("antihaldane_2")
        self.gridLayout_10.addWidget(self.antihaldane_2, 8, 1, 1, 1)
        self.By_2 = QtWidgets.QLineEdit(self.tab_11)
        self.By_2.setObjectName("By_2")
        self.gridLayout_10.addWidget(self.By_2, 3, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_11)
        self.label_32.setObjectName("label_32")
        self.gridLayout_10.addWidget(self.label_32, 5, 0, 1, 1)
        self.kanemele_2 = QtWidgets.QLineEdit(self.tab_11)
        self.kanemele_2.setObjectName("kanemele_2")
        self.gridLayout_10.addWidget(self.kanemele_2, 6, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_11)
        self.label_39.setObjectName("label_39")
        self.gridLayout_10.addWidget(self.label_39, 10, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_11)
        self.label_33.setObjectName("label_33")
        self.gridLayout_10.addWidget(self.label_33, 6, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_11)
        self.label_37.setObjectName("label_37")
        self.gridLayout_10.addWidget(self.label_37, 0, 0, 1, 1)
        self.rashba_2 = QtWidgets.QLineEdit(self.tab_11)
        self.rashba_2.setObjectName("rashba_2")
        self.gridLayout_10.addWidget(self.rashba_2, 5, 1, 1, 1)
        self.swave_2 = QtWidgets.QLineEdit(self.tab_11)
        self.swave_2.setObjectName("swave_2")
        self.gridLayout_10.addWidget(self.swave_2, 11, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_11)
        self.label_40.setObjectName("label_40")
        self.gridLayout_10.addWidget(self.label_40, 8, 0, 1, 1)
        self.peierls_2 = QtWidgets.QLineEdit(self.tab_11)
        self.peierls_2.setObjectName("peierls_2")
        self.gridLayout_10.addWidget(self.peierls_2, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_11)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_11, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mAF = QtWidgets.QLineEdit(self.tab_8)
        self.mAF.setObjectName("mAF")
        self.gridLayout.addWidget(self.mAF, 10, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_8)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_8)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_8)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_8)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 8, 0, 1, 1)
        self.kanemele = QtWidgets.QLineEdit(self.tab_8)
        self.kanemele.setObjectName("kanemele")
        self.gridLayout.addWidget(self.kanemele, 6, 1, 1, 1)
        self.haldane = QtWidgets.QLineEdit(self.tab_8)
        self.haldane.setObjectName("haldane")
        self.gridLayout.addWidget(self.haldane, 7, 1, 1, 1)
        self.Bz = QtWidgets.QLineEdit(self.tab_8)
        self.Bz.setObjectName("Bz")
        self.gridLayout.addWidget(self.Bz, 4, 1, 1, 1)
        self.By = QtWidgets.QLineEdit(self.tab_8)
        self.By.setObjectName("By")
        self.gridLayout.addWidget(self.By, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_8)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_8)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_8)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.fermi = QtWidgets.QLineEdit(self.tab_8)
        self.fermi.setEnabled(True)
        self.fermi.setObjectName("fermi")
        self.gridLayout.addWidget(self.fermi, 0, 1, 1, 1)
        self.mAB = QtWidgets.QLineEdit(self.tab_8)
        self.mAB.setObjectName("mAB")
        self.gridLayout.addWidget(self.mAB, 9, 1, 1, 1)
        self.rashba = QtWidgets.QLineEdit(self.tab_8)
        self.rashba.setObjectName("rashba")
        self.gridLayout.addWidget(self.rashba, 5, 1, 1, 1)
        self.Bx = QtWidgets.QLineEdit(self.tab_8)
        self.Bx.setObjectName("Bx")
        self.gridLayout.addWidget(self.Bx, 2, 1, 1, 1)
        self.antihaldane = QtWidgets.QLineEdit(self.tab_8)
        self.antihaldane.setObjectName("antihaldane")
        self.gridLayout.addWidget(self.antihaldane, 8, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_8)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 9, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_8)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 7, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_8)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 11, 0, 1, 1)
        self.swave = QtWidgets.QLineEdit(self.tab_8)
        self.swave.setObjectName("swave")
        self.gridLayout.addWidget(self.swave, 11, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_8)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_8)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.peierls = QtWidgets.QLineEdit(self.tab_8)
        self.peierls.setObjectName("peierls")
        self.gridLayout.addWidget(self.peierls, 1, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_8, "")
        self.gridLayout_15.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.gridLayout_7.addWidget(self.tabWidget_2, 0, 0, 3, 1)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.nsuper_struct = QtWidgets.QLineEdit(self.tab_4)
        self.nsuper_struct.setObjectName("nsuper_struct")
        self.gridLayout_3.addWidget(self.nsuper_struct, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.show_structure = QtWidgets.QPushButton(self.tab_4)
        self.show_structure.setObjectName("show_structure")
        self.gridLayout_8.addWidget(self.show_structure, 1, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.bands_color = QtWidgets.QComboBox(self.tab_5)
        self.bands_color.setObjectName("bands_color")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.gridLayout_2.addWidget(self.bands_color, 0, 1, 1, 1)
        self.nk_bands = QtWidgets.QLineEdit(self.tab_5)
        self.nk_bands.setObjectName("nk_bands")
        self.gridLayout_2.addWidget(self.nk_bands, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.show_bands = QtWidgets.QPushButton(self.tab_5)
        self.show_bands.setObjectName("show_bands")
        self.gridLayout_9.addWidget(self.show_bands, 1, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.delta_kbands = QtWidgets.QLineEdit(self.tab_9)
        self.delta_kbands.setObjectName("delta_kbands")
        self.gridLayout_11.addWidget(self.delta_kbands, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_9)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 0, 0, 1, 1)
        self.ne_kbands = QtWidgets.QLineEdit(self.tab_9)
        self.ne_kbands.setObjectName("ne_kbands")
        self.gridLayout_11.addWidget(self.ne_kbands, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_9)
        self.label_28.setObjectName("label_28")
        self.gridLayout_11.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_9)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 2, 0, 1, 1)
        self.window_kbands = QtWidgets.QLineEdit(self.tab_9)
        self.window_kbands.setObjectName("window_kbands")
        self.gridLayout_11.addWidget(self.window_kbands, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_9)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 3, 0, 1, 1)
        self.scale_kbands = QtWidgets.QLineEdit(self.tab_9)
        self.scale_kbands.setObjectName("scale_kbands")
        self.gridLayout_11.addWidget(self.scale_kbands, 3, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_9)
        self.label_31.setObjectName("label_31")
        self.gridLayout_11.addWidget(self.label_31, 4, 0, 1, 1)
        self.nv_kbands = QtWidgets.QLineEdit(self.tab_9)
        self.nv_kbands.setObjectName("nv_kbands")
        self.gridLayout_11.addWidget(self.nv_kbands, 4, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.show_dosbands = QtWidgets.QPushButton(self.tab_9)
        self.show_dosbands.setObjectName("show_dosbands")
        self.gridLayout_12.addWidget(self.show_dosbands, 0, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.dos_delta = QtWidgets.QLineEdit(self.tab_6)
        self.dos_delta.setObjectName("dos_delta")
        self.gridLayout_5.addWidget(self.dos_delta, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_6)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 1, 0, 1, 1)
        self.dos_nk = QtWidgets.QLineEdit(self.tab_6)
        self.dos_nk.setObjectName("dos_nk")
        self.gridLayout_5.addWidget(self.dos_nk, 1, 1, 1, 1)
        self.dos_ewindow = QtWidgets.QLineEdit(self.tab_6)
        self.dos_ewindow.setObjectName("dos_ewindow")
        self.gridLayout_5.addWidget(self.dos_ewindow, 2, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_6)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 2, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.show_dos = QtWidgets.QPushButton(self.tab_6)
        self.show_dos.setObjectName("show_dos")
        self.gridLayout_13.addWidget(self.show_dos, 1, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ne_ldos = QtWidgets.QLineEdit(self.tab_7)
        self.ne_ldos.setObjectName("ne_ldos")
        self.gridLayout_6.addWidget(self.ne_ldos, 0, 1, 1, 1)
        self.delta_ldos = QtWidgets.QLineEdit(self.tab_7)
        self.delta_ldos.setObjectName("delta_ldos")
        self.gridLayout_6.addWidget(self.delta_ldos, 3, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 3, 0, 1, 1)
        self.nk_ldos = QtWidgets.QLineEdit(self.tab_7)
        self.nk_ldos.setObjectName("nk_ldos")
        self.gridLayout_6.addWidget(self.nk_ldos, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_7)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_7)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 2, 0, 1, 1)
        self.window_ldos = QtWidgets.QLineEdit(self.tab_7)
        self.window_ldos.setObjectName("window_ldos")
        self.gridLayout_6.addWidget(self.window_ldos, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_7)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 4, 0, 1, 1)
        self.nsuper_ldos = QtWidgets.QLineEdit(self.tab_7)
        self.nsuper_ldos.setObjectName("nsuper_ldos")
        self.gridLayout_6.addWidget(self.nsuper_ldos, 4, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.show_interactive_ldos = QtWidgets.QPushButton(self.tab_7)
        self.show_interactive_ldos.setObjectName("show_interactive_ldos")
        self.gridLayout_14.addWidget(self.show_interactive_ldos, 0, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.gridLayout_7.addWidget(self.tabWidget_3, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.lattice = QtWidgets.QComboBox(self.tab_2)
        self.lattice.setObjectName("lattice")
        self.lattice.addItem("")
        self.lattice.addItem("")
        self.lattice.addItem("")
        self.lattice.addItem("")
        self.lattice.addItem("")
        self.lattice.addItem("")
        self.lattice.addItem("")
        self.gridLayout_4.addWidget(self.lattice, 0, 1, 1, 1)
        self.nsuper = QtWidgets.QLineEdit(self.tab_2)
        self.nsuper.setObjectName("nsuper")
        self.gridLayout_4.addWidget(self.nsuper, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.width = QtWidgets.QLineEdit(self.tab_2)
        self.width.setObjectName("width")
        self.gridLayout_4.addWidget(self.width, 2, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_7.addWidget(self.tabWidget, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setObjectName("label_46")
        self.gridLayout_7.addWidget(self.label_46, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.bands_color.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hybrid ribbon"))
        self.label_38.setText(_translate("MainWindow", "Zeeman Jz"))
        self.Bz_2.setText(_translate("MainWindow", "0.0"))
        self.mAF_2.setText(_translate("MainWindow", "0.0"))
        self.label_42.setText(_translate("MainWindow", "swave pairing"))
        self.label_36.setText(_translate("MainWindow", "Zeeman Jx"))
        self.Bx_2.setText(_translate("MainWindow", "0.0"))
        self.label_22.setText(_translate("MainWindow", "Sublattice imbalance"))
        self.fermi_2.setText(_translate("MainWindow", "0.0"))
        self.label_34.setText(_translate("MainWindow", "Zeeman Jy"))
        self.mAB_2.setText(_translate("MainWindow", "0.0"))
        self.label_41.setText(_translate("MainWindow", "Haldane"))
        self.haldane_2.setText(_translate("MainWindow", "0.0"))
        self.antihaldane_2.setText(_translate("MainWindow", "0.0"))
        self.By_2.setText(_translate("MainWindow", "0.0"))
        self.label_32.setText(_translate("MainWindow", "Rashba"))
        self.kanemele_2.setText(_translate("MainWindow", "0.0"))
        self.label_39.setText(_translate("MainWindow", "Antiferromagnetism"))
        self.label_33.setText(_translate("MainWindow", "Kane-Mele"))
        self.label_37.setText(_translate("MainWindow", "Fermi energy"))
        self.rashba_2.setText(_translate("MainWindow", "0.0"))
        self.swave_2.setText(_translate("MainWindow", "0.0"))
        self.label_40.setText(_translate("MainWindow", "Anti-Haldane"))
        self.peierls_2.setText(_translate("MainWindow", "0.0"))
        self.label_19.setText(_translate("MainWindow", "Magnetic field"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("MainWindow", "Lower"))
        self.mAF.setText(_translate("MainWindow", "0.0"))
        self.label_10.setText(_translate("MainWindow", "Rashba"))
        self.label_13.setText(_translate("MainWindow", "Antiferromagnetism"))
        self.label_5.setText(_translate("MainWindow", "Zeeman Jz"))
        self.label_25.setText(_translate("MainWindow", "Anti-Haldane"))
        self.kanemele.setText(_translate("MainWindow", "0.0"))
        self.haldane.setText(_translate("MainWindow", "0.0"))
        self.Bz.setText(_translate("MainWindow", "0.0"))
        self.By.setText(_translate("MainWindow", "0.0"))
        self.label.setText(_translate("MainWindow", "Fermi energy"))
        self.label_11.setText(_translate("MainWindow", "Kane-Mele"))
        self.label_4.setText(_translate("MainWindow", "Zeeman Jy"))
        self.fermi.setText(_translate("MainWindow", "0.0"))
        self.mAB.setText(_translate("MainWindow", "0.0"))
        self.rashba.setText(_translate("MainWindow", "0.0"))
        self.Bx.setText(_translate("MainWindow", "0.0"))
        self.antihaldane.setText(_translate("MainWindow", "0.0"))
        self.label_12.setText(_translate("MainWindow", "Sublattice imbalance"))
        self.label_24.setText(_translate("MainWindow", "Haldane"))
        self.label_26.setText(_translate("MainWindow", "swave pairing"))
        self.swave.setText(_translate("MainWindow", "0.0"))
        self.label_3.setText(_translate("MainWindow", "Zeeman Jx"))
        self.label_14.setText(_translate("MainWindow", "Magnetic field"))
        self.peierls.setText(_translate("MainWindow", "0.0"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_8), _translate("MainWindow", "Upper"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Terms in the Hamiltonian"))
        self.label_7.setText(_translate("MainWindow", "Supercell"))
        self.nsuper_struct.setText(_translate("MainWindow", "5"))
        self.show_structure.setText(_translate("MainWindow", "Show structure"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("MainWindow", "Structure"))
        self.label_9.setText(_translate("MainWindow", "# kpoints"))
        self.label_15.setText(_translate("MainWindow", "Operator"))
        self.bands_color.setItemText(0, _translate("MainWindow", "None"))
        self.bands_color.setItemText(1, _translate("MainWindow", "y-position"))
        self.bands_color.setItemText(2, _translate("MainWindow", "Sx"))
        self.bands_color.setItemText(3, _translate("MainWindow", "Sy"))
        self.bands_color.setItemText(4, _translate("MainWindow", "Sz"))
        self.bands_color.setItemText(5, _translate("MainWindow", "Valley"))
        self.bands_color.setItemText(6, _translate("MainWindow", "IPR"))
        self.nk_bands.setText(_translate("MainWindow", "100"))
        self.show_bands.setText(_translate("MainWindow", "Band structure"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Bands"))
        self.delta_kbands.setText(_translate("MainWindow", "0.01"))
        self.label_27.setText(_translate("MainWindow", "Smearing"))
        self.ne_kbands.setText(_translate("MainWindow", "400"))
        self.label_28.setText(_translate("MainWindow", "# of energies"))
        self.label_29.setText(_translate("MainWindow", "Energy window"))
        self.window_kbands.setText(_translate("MainWindow", "3.0"))
        self.label_30.setText(_translate("MainWindow", "KPM scale"))
        self.scale_kbands.setText(_translate("MainWindow", "10.0"))
        self.label_31.setText(_translate("MainWindow", "# vectors"))
        self.nv_kbands.setText(_translate("MainWindow", "10"))
        self.show_dosbands.setToolTip(_translate("MainWindow", "This is equivalent to band structure calculation, but it can be applied for very large systems"))
        self.show_dosbands.setText(_translate("MainWindow", "Show DOS Bands"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "DOS Bands"))
        self.label_16.setText(_translate("MainWindow", "Smearing"))
        self.dos_delta.setText(_translate("MainWindow", "0.01"))
        self.label_43.setText(_translate("MainWindow", "Number of k-points"))
        self.dos_nk.setText(_translate("MainWindow", "400"))
        self.dos_ewindow.setText(_translate("MainWindow", "4.0"))
        self.label_44.setText(_translate("MainWindow", "Energy window"))
        self.show_dos.setText(_translate("MainWindow", "Density of states"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "DOS"))
        self.ne_ldos.setText(_translate("MainWindow", "300"))
        self.delta_ldos.setText(_translate("MainWindow", "0.03"))
        self.label_35.setText(_translate("MainWindow", "Smearing"))
        self.nk_ldos.setText(_translate("MainWindow", "20"))
        self.label_17.setText(_translate("MainWindow", "# of energies"))
        self.label_18.setText(_translate("MainWindow", "# of kpoints"))
        self.label_55.setText(_translate("MainWindow", "Energy window"))
        self.window_ldos.setText(_translate("MainWindow", "0.5"))
        self.label_56.setText(_translate("MainWindow", "Supercell"))
        self.nsuper_ldos.setText(_translate("MainWindow", "5"))
        self.show_interactive_ldos.setText(_translate("MainWindow", "Show LDOS"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "LDOS"))
        self.label_8.setText(_translate("MainWindow", "Type of lattice"))
        self.lattice.setItemText(0, _translate("MainWindow", "Honeycomb zigzag"))
        self.lattice.setItemText(1, _translate("MainWindow", "Honeycomb armchair"))
        self.lattice.setItemText(2, _translate("MainWindow", "Square"))
        self.lattice.setItemText(3, _translate("MainWindow", "Triangular"))
        self.lattice.setItemText(4, _translate("MainWindow", "Kagome"))
        self.lattice.setItemText(5, _translate("MainWindow", "Lieb"))
        self.lattice.setItemText(6, _translate("MainWindow", "Chain"))
        self.nsuper.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "Supercell"))
        self.label_2.setText(_translate("MainWindow", "Width"))
        self.width.setText(_translate("MainWindow", "10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Geometry"))
        self.label_46.setToolTip(_translate("MainWindow", "This module allows to compute heterostructures consisting of two different films. You have to specify the parameters of the two films"))
        self.label_46.setText(_translate("MainWindow", "About"))

