# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tab_12)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_12)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_12)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.tinter = QtWidgets.QLineEdit(self.tab_12)
        self.tinter.setObjectName("tinter")
        self.gridLayout.addWidget(self.tinter, 0, 1, 1, 1)
        self.interlayer_bias = QtWidgets.QLineEdit(self.tab_12)
        self.interlayer_bias.setObjectName("interlayer_bias")
        self.gridLayout.addWidget(self.interlayer_bias, 1, 1, 1, 1)
        self.fermi = QtWidgets.QLineEdit(self.tab_12)
        self.fermi.setObjectName("fermi")
        self.gridLayout.addWidget(self.fermi, 2, 1, 1, 1)
        self.set_half_filling = QtWidgets.QRadioButton(self.tab_12)
        self.set_half_filling.setObjectName("set_half_filling")
        self.gridLayout.addWidget(self.set_half_filling, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_12)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.crystalfield = QtWidgets.QLineEdit(self.tab_12)
        self.crystalfield.setObjectName("crystalfield")
        self.gridLayout.addWidget(self.crystalfield, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_12)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 5, 0, 1, 1)
        self.inplaneb_phi = QtWidgets.QLineEdit(self.tab_12)
        self.inplaneb_phi.setObjectName("inplaneb_phi")
        self.gridLayout.addWidget(self.inplaneb_phi, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_12)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.inplaneb = QtWidgets.QLineEdit(self.tab_12)
        self.inplaneb.setEnabled(False)
        self.inplaneb.setObjectName("inplaneb")
        self.gridLayout.addWidget(self.inplaneb, 4, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_12, "")
        self.gridLayout_17.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.show_structure = QtWidgets.QPushButton(self.tab_2)
        self.show_structure.setObjectName("show_structure")
        self.gridLayout_8.addWidget(self.show_structure, 1, 0, 1, 1)
        self.show_structure_3d = QtWidgets.QPushButton(self.tab_2)
        self.show_structure_3d.setObjectName("show_structure_3d")
        self.gridLayout_8.addWidget(self.show_structure_3d, 1, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.nsuper_struct = QtWidgets.QLineEdit(self.tab_2)
        self.nsuper_struct.setObjectName("nsuper_struct")
        self.gridLayout_5.addWidget(self.nsuper_struct, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.nbands = QtWidgets.QLineEdit(self.tab)
        self.nbands.setObjectName("nbands")
        self.gridLayout_3.addWidget(self.nbands, 2, 1, 1, 1)
        self.nk_bands = QtWidgets.QLineEdit(self.tab)
        self.nk_bands.setObjectName("nk_bands")
        self.gridLayout_3.addWidget(self.nk_bands, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.bands_color = QtWidgets.QComboBox(self.tab)
        self.bands_color.setObjectName("bands_color")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.gridLayout_3.addWidget(self.bands_color, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.show_bands = QtWidgets.QPushButton(self.tab)
        self.show_bands.setObjectName("show_bands")
        self.gridLayout_9.addWidget(self.show_bands, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.delta_ldos_single = QtWidgets.QLineEdit(self.tab_3)
        self.delta_ldos_single.setObjectName("delta_ldos_single")
        self.gridLayout_4.addWidget(self.delta_ldos_single, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.nsuper_ldos_single = QtWidgets.QLineEdit(self.tab_3)
        self.nsuper_ldos_single.setObjectName("nsuper_ldos_single")
        self.gridLayout_4.addWidget(self.nsuper_ldos_single, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.energy_ldos_single = QtWidgets.QLineEdit(self.tab_3)
        self.energy_ldos_single.setObjectName("energy_ldos_single")
        self.gridLayout_4.addWidget(self.energy_ldos_single, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 2, 0, 1, 1)
        self.nk_ldos_single = QtWidgets.QLineEdit(self.tab_3)
        self.nk_ldos_single.setObjectName("nk_ldos_single")
        self.gridLayout_4.addWidget(self.nk_ldos_single, 2, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.show_ldos_single = QtWidgets.QPushButton(self.tab_3)
        self.show_ldos_single.setObjectName("show_ldos_single")
        self.gridLayout_10.addWidget(self.show_ldos_single, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.multildos_nk = QtWidgets.QLineEdit(self.tab_7)
        self.multildos_nk.setObjectName("multildos_nk")
        self.gridLayout_18.addWidget(self.multildos_nk, 1, 1, 1, 1)
        self.multildos_delta = QtWidgets.QLineEdit(self.tab_7)
        self.multildos_delta.setObjectName("multildos_delta")
        self.gridLayout_18.addWidget(self.multildos_delta, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_18.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_7)
        self.label_24.setObjectName("label_24")
        self.gridLayout_18.addWidget(self.label_24, 0, 0, 1, 1)
        self.show_multildos = QtWidgets.QPushButton(self.tab_7)
        self.show_multildos.setObjectName("show_multildos")
        self.gridLayout_18.addWidget(self.show_multildos, 5, 0, 1, 2)
        self.multildos_ewindow = QtWidgets.QLineEdit(self.tab_7)
        self.multildos_ewindow.setObjectName("multildos_ewindow")
        self.gridLayout_18.addWidget(self.multildos_ewindow, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_7)
        self.label_25.setObjectName("label_25")
        self.gridLayout_18.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_7)
        self.label_26.setObjectName("label_26")
        self.gridLayout_18.addWidget(self.label_26, 2, 0, 1, 1)
        self.multildos_nrep = QtWidgets.QLineEdit(self.tab_7)
        self.multildos_nrep.setObjectName("multildos_nrep")
        self.gridLayout_18.addWidget(self.multildos_nrep, 2, 1, 1, 1)
        self.multildos_numw = QtWidgets.QLineEdit(self.tab_7)
        self.multildos_numw.setObjectName("multildos_numw")
        self.gridLayout_18.addWidget(self.multildos_numw, 3, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_7)
        self.label_32.setObjectName("label_32")
        self.gridLayout_18.addWidget(self.label_32, 3, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.show_dos = QtWidgets.QPushButton(self.tab_4)
        self.show_dos.setObjectName("show_dos")
        self.gridLayout_12.addWidget(self.show_dos, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.delta_dos = QtWidgets.QLineEdit(self.tab_4)
        self.delta_dos.setEnabled(True)
        self.delta_dos.setObjectName("delta_dos")
        self.gridLayout_6.addWidget(self.delta_dos, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setEnabled(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.nk_dos = QtWidgets.QLineEdit(self.tab_4)
        self.nk_dos.setObjectName("nk_dos")
        self.gridLayout_6.addWidget(self.nk_dos, 1, 1, 1, 1)
        self.mode_dos = QtWidgets.QComboBox(self.tab_4)
        self.mode_dos.setObjectName("mode_dos")
        self.mode_dos.addItem("")
        self.mode_dos.addItem("")
        self.gridLayout_6.addWidget(self.mode_dos, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 2, 0, 1, 1)
        self.numw_dos = QtWidgets.QLineEdit(self.tab_4)
        self.numw_dos.setObjectName("numw_dos")
        self.gridLayout_6.addWidget(self.numw_dos, 2, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.fs_nk = QtWidgets.QLineEdit(self.tab_6)
        self.fs_nk.setObjectName("fs_nk")
        self.gridLayout_15.addWidget(self.fs_nk, 2, 1, 1, 1)
        self.fs_ewindow = QtWidgets.QLineEdit(self.tab_6)
        self.fs_ewindow.setObjectName("fs_ewindow")
        self.gridLayout_15.addWidget(self.fs_ewindow, 0, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.tab_6)
        self.label_52.setObjectName("label_52")
        self.gridLayout_15.addWidget(self.label_52, 2, 0, 1, 1)
        self.show_fermi_surface = QtWidgets.QPushButton(self.tab_6)
        self.show_fermi_surface.setObjectName("show_fermi_surface")
        self.gridLayout_15.addWidget(self.show_fermi_surface, 4, 0, 1, 2)
        self.label_49 = QtWidgets.QLabel(self.tab_6)
        self.label_49.setObjectName("label_49")
        self.gridLayout_15.addWidget(self.label_49, 1, 0, 1, 1)
        self.fs_delta = QtWidgets.QLineEdit(self.tab_6)
        self.fs_delta.setObjectName("fs_delta")
        self.gridLayout_15.addWidget(self.fs_delta, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_6)
        self.label_42.setObjectName("label_42")
        self.gridLayout_15.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_15.addWidget(self.label_22, 3, 0, 1, 1)
        self.fs_numw = QtWidgets.QLineEdit(self.tab_6)
        self.fs_numw.setObjectName("fs_numw")
        self.gridLayout_15.addWidget(self.fs_numw, 3, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.delta_kbands = QtWidgets.QLineEdit(self.tab_5)
        self.delta_kbands.setObjectName("delta_kbands")
        self.gridLayout_11.addWidget(self.delta_kbands, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 3, 0, 1, 1)
        self.window_kbands = QtWidgets.QLineEdit(self.tab_5)
        self.window_kbands.setObjectName("window_kbands")
        self.gridLayout_11.addWidget(self.window_kbands, 3, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_11.addWidget(self.label_31, 5, 0, 1, 1)
        self.nv_kbands = QtWidgets.QLineEdit(self.tab_5)
        self.nv_kbands.setObjectName("nv_kbands")
        self.gridLayout_11.addWidget(self.nv_kbands, 5, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 1, 0, 1, 1)
        self.ne_kbands = QtWidgets.QLineEdit(self.tab_5)
        self.ne_kbands.setObjectName("ne_kbands")
        self.gridLayout_11.addWidget(self.ne_kbands, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_11.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 4, 0, 1, 1)
        self.scale_kbands = QtWidgets.QLineEdit(self.tab_5)
        self.scale_kbands.setObjectName("scale_kbands")
        self.gridLayout_11.addWidget(self.scale_kbands, 4, 1, 1, 1)
        self.nk_kbands = QtWidgets.QLineEdit(self.tab_5)
        self.nk_kbands.setObjectName("nk_kbands")
        self.gridLayout_11.addWidget(self.nk_kbands, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.show_dosbands = QtWidgets.QPushButton(self.tab_5)
        self.show_dosbands.setObjectName("show_dosbands")
        self.gridLayout_13.addWidget(self.show_dosbands, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_17.addWidget(self.tabWidget, 0, 1, 2, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab_8)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.cell_size = QtWidgets.QLineEdit(self.tab_8)
        self.cell_size.setObjectName("cell_size")
        self.gridLayout_2.addWidget(self.cell_size, 0, 1, 1, 1)
        self.multilayer_type = QtWidgets.QComboBox(self.tab_8)
        self.multilayer_type.setObjectName("multilayer_type")
        self.gridLayout_2.addWidget(self.multilayer_type, 1, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_8)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.remove_single_bonded = QtWidgets.QCheckBox(self.tab_9)
        self.remove_single_bonded.setEnabled(True)
        self.remove_single_bonded.setChecked(False)
        self.remove_single_bonded.setObjectName("remove_single_bonded")
        self.gridLayout_27.addWidget(self.remove_single_bonded, 0, 0, 1, 1)
        self.remove_selected = QtWidgets.QCheckBox(self.tab_9)
        self.remove_selected.setObjectName("remove_selected")
        self.gridLayout_27.addWidget(self.remove_selected, 1, 0, 1, 1)
        self.select_atoms_removal = QtWidgets.QPushButton(self.tab_9)
        self.select_atoms_removal.setObjectName("select_atoms_removal")
        self.gridLayout_27.addWidget(self.select_atoms_removal, 2, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_27)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.gridLayout_17.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.use_parallelization = QtWidgets.QComboBox(self.centralwidget)
        self.use_parallelization.setObjectName("use_parallelization")
        self.use_parallelization.addItem("")
        self.use_parallelization.addItem("")
        self.gridLayout_7.addWidget(self.use_parallelization, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_7, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Twisted multilayer graphene"))
        self.label.setText(_translate("MainWindow", "Interlayer"))
        self.label_2.setText(_translate("MainWindow", "Electric bias"))
        self.label_4.setText(_translate("MainWindow", "Fermi energy"))
        self.tinter.setText(_translate("MainWindow", "0.4"))
        self.interlayer_bias.setText(_translate("MainWindow", "0.0"))
        self.fermi.setText(_translate("MainWindow", "0.0"))
        self.set_half_filling.setText(_translate("MainWindow", "Measure with respect to half filling"))
        self.label_3.setText(_translate("MainWindow", "Crystal field"))
        self.crystalfield.setToolTip(_translate("MainWindow", "Crystal field Hartree term, makes the edge atoms inequivalent"))
        self.crystalfield.setText(_translate("MainWindow", "0.0"))
        self.label_20.setText(_translate("MainWindow", "Angle inplane B field"))
        self.inplaneb_phi.setText(_translate("MainWindow", "0.0"))
        self.label_18.setText(_translate("MainWindow", "Inplane B field"))
        self.inplaneb.setText(_translate("MainWindow", "0.0"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("MainWindow", "Hamiltonian"))
        self.show_structure.setText(_translate("MainWindow", "Show structure"))
        self.show_structure_3d.setText(_translate("MainWindow", "Show structure 3D"))
        self.nsuper_struct.setText(_translate("MainWindow", "6"))
        self.label_12.setText(_translate("MainWindow", "Supercell"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Structure"))
        self.label_7.setText(_translate("MainWindow", "nbands"))
        self.label_6.setText(_translate("MainWindow", "nkpoints"))
        self.nbands.setText(_translate("MainWindow", "20"))
        self.nk_bands.setText(_translate("MainWindow", "100"))
        self.label_16.setText(_translate("MainWindow", "Operator"))
        self.bands_color.setItemText(0, _translate("MainWindow", "None"))
        self.bands_color.setItemText(1, _translate("MainWindow", "Valley"))
        self.bands_color.setItemText(2, _translate("MainWindow", "IPR"))
        self.bands_color.setItemText(3, _translate("MainWindow", "Layer"))
        self.bands_color.setItemText(4, _translate("MainWindow", "Berry"))
        self.show_bands.setText(_translate("MainWindow", "Bandstructure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Bands"))
        self.delta_ldos_single.setText(_translate("MainWindow", "0.01"))
        self.label_9.setText(_translate("MainWindow", "Energy"))
        self.nsuper_ldos_single.setText(_translate("MainWindow", "3"))
        self.label_10.setText(_translate("MainWindow", "Supercell"))
        self.energy_ldos_single.setText(_translate("MainWindow", "0.0"))
        self.label_8.setText(_translate("MainWindow", "Smearing"))
        self.label_11.setText(_translate("MainWindow", "# kpoints"))
        self.nk_ldos_single.setText(_translate("MainWindow", "10"))
        self.show_ldos_single.setText(_translate("MainWindow", "Show LDOS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Single LDOS"))
        self.multildos_nk.setToolTip(_translate("MainWindow", "Number of kpoints used"))
        self.multildos_nk.setText(_translate("MainWindow", "10"))
        self.multildos_delta.setToolTip(_translate("MainWindow", "Energy smearing"))
        self.multildos_delta.setText(_translate("MainWindow", "0.003"))
        self.label_23.setText(_translate("MainWindow", "Smearing"))
        self.label_24.setText(_translate("MainWindow", "Energy window"))
        self.show_multildos.setText(_translate("MainWindow", "Show LDOS"))
        self.multildos_ewindow.setToolTip(_translate("MainWindow", "Energy window"))
        self.multildos_ewindow.setText(_translate("MainWindow", "0.3"))
        self.label_25.setText(_translate("MainWindow", "Number of kpoints"))
        self.label_26.setText(_translate("MainWindow", "Number of unit cells"))
        self.multildos_nrep.setToolTip(_translate("MainWindow", "Number of replicas of the unit cell to plot"))
        self.multildos_nrep.setText(_translate("MainWindow", "6"))
        self.multildos_numw.setToolTip(_translate("MainWindow", "Number of wavefunctions computed around E=0 to calculate the LDOS"))
        self.multildos_numw.setText(_translate("MainWindow", "20"))
        self.label_32.setText(_translate("MainWindow", "Number of waves"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "LDOS"))
        self.show_dos.setText(_translate("MainWindow", "Show DOS"))
        self.delta_dos.setText(_translate("MainWindow", "0.005"))
        self.label_17.setText(_translate("MainWindow", "# kpoints"))
        self.label_13.setText(_translate("MainWindow", "Smearing"))
        self.nk_dos.setText(_translate("MainWindow", "100"))
        self.mode_dos.setItemText(0, _translate("MainWindow", "Lowest"))
        self.mode_dos.setItemText(1, _translate("MainWindow", "KPM"))
        self.label_14.setText(_translate("MainWindow", "Calculation mode"))
        self.label_15.setText(_translate("MainWindow", "# of waves for Lowest mode"))
        self.numw_dos.setToolTip(_translate("MainWindow", "Number of wavefunctions used for the calculation of DOS for the Lowest mode. Increase to see a bigger energy window"))
        self.numw_dos.setText(_translate("MainWindow", "20"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "DOS"))
        self.fs_nk.setText(_translate("MainWindow", "60"))
        self.fs_ewindow.setText(_translate("MainWindow", "0.05"))
        self.label_52.setText(_translate("MainWindow", "Number of kpoints"))
        self.show_fermi_surface.setText(_translate("MainWindow", "Show Fermi surface"))
        self.label_49.setText(_translate("MainWindow", "Smearing"))
        self.fs_delta.setText(_translate("MainWindow", "0.0005"))
        self.label_42.setText(_translate("MainWindow", "Energy window"))
        self.label_22.setText(_translate("MainWindow", "Number of waves"))
        self.fs_numw.setText(_translate("MainWindow", "8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "FS"))
        self.delta_kbands.setText(_translate("MainWindow", "0.01"))
        self.label_29.setText(_translate("MainWindow", "Energy window"))
        self.window_kbands.setText(_translate("MainWindow", "0.5"))
        self.label_31.setText(_translate("MainWindow", "# vectors"))
        self.nv_kbands.setToolTip(_translate("MainWindow", "Number of vectors in KPM, increase this number to remove noise"))
        self.nv_kbands.setText(_translate("MainWindow", "2"))
        self.label_27.setText(_translate("MainWindow", "Smearing"))
        self.ne_kbands.setText(_translate("MainWindow", "400"))
        self.label_28.setText(_translate("MainWindow", "# of energies"))
        self.label_30.setText(_translate("MainWindow", "KPM scale"))
        self.scale_kbands.setText(_translate("MainWindow", "4.0"))
        self.nk_kbands.setText(_translate("MainWindow", "100"))
        self.label_19.setText(_translate("MainWindow", "# of kpoints"))
        self.show_dosbands.setToolTip(_translate("MainWindow", "This is equivalent to band structure calculation, but it can be applied for very large systems"))
        self.show_dosbands.setText(_translate("MainWindow", "Show DOS Bands"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "DOS Bands"))
        self.label_5.setText(_translate("MainWindow", "Cell size"))
        self.cell_size.setText(_translate("MainWindow", "7"))
        self.label_33.setText(_translate("MainWindow", "Multilayer type"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Geometry"))
        self.remove_single_bonded.setToolTip(_translate("MainWindow", "Remove atoms that have a single bond in the structure"))
        self.remove_single_bonded.setText(_translate("MainWindow", "Remove single bonds"))
        self.remove_selected.setText(_translate("MainWindow", "Remove selected atoms"))
        self.select_atoms_removal.setText(_translate("MainWindow", "Select atoms to remove"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Modify geometry"))
        self.use_parallelization.setItemText(0, _translate("MainWindow", "Yes"))
        self.use_parallelization.setItemText(1, _translate("MainWindow", "No"))
        self.label_21.setText(_translate("MainWindow", "Parallelization"))

