###############################################
###############################################
###############################################
#### This file has simple wrappers to qt5  ####
###############################################
###############################################
###############################################



from PyQt5 import QtWidgets  # Import the PyQt5 module we'll need
from PyQt5.QtGui import QPixmap
#from PyQt5.QtCore import Signal
import sys  # We need sys so that we can pass argv to QApplication
import numpy as np
import os
import time
import inspect
import json

from numpy import * # this may not be a good idea
from .qlinterface import running
from .debugging import holler

# This file holds our MainWindow and all interface related things
import interface # this file is generated by Qt-designer 

QtGui = QtWidgets
app = QtWidgets.QApplication(sys.argv)  # A new instance of QApplication


def get_failsafe(f,robust=True):
    """Return a function that if fails things do not break down"""
    def fout(*args,**kwargs):
        if not robust: return f()
        try: f()
        except: 
            if holler(): print("Something wrong happened")
            return None
    return fout



class App(QtGui.QMainWindow, interface.Ui_MainWindow):
    def __init__(self):
        super(self.__class__, self).__init__()
        self.setupUi(self)  # This is defined in interface.py file automatically
        # It sets up layout and widgets that are defined
        self._params_dirty_time = time.time() # results are stale before this
        self._connect_dirty_tracking()
    def _connect_dirty_tracking(self):
        """Mark parameters as changed only on genuine user interaction,
        never on programmatic updates (e.g. a handler writing a computed
        value into a QLineEdit), so freshly computed results aren't
        mistaken for stale ones."""
        for name,obj in inspect.getmembers(self):
            if isinstance(obj,QtWidgets.QLineEdit):
                obj.textEdited.connect(self._mark_dirty)
            elif isinstance(obj,QtWidgets.QComboBox):
                obj.activated.connect(self._mark_dirty)
            elif isinstance(obj,(QtWidgets.QCheckBox,QtWidgets.QRadioButton)):
                obj.clicked.connect(self._mark_dirty)
    def _mark_dirty(self,*args):
        self._params_dirty_time = time.time()
    def reset_dirty(self):
        """Mark current results as valid for the current parameters"""
        self._params_dirty_time = time.time()
    def params_dirty_time(self):
        return self._params_dirty_time
    def save_interface(self,**kwargs):
        save_interface(self,**kwargs)
    def load_interface(self,*args,**kwargs):
        load_interface(self,*args,**kwargs)
    def run(self):
        self.show()  # Show the form
        app.exec_()  # and execute the app
    def get(self,*args,**kwargs):
        return get(*args,**kwargs)
    def set(self,*args):
        set_value(*args)
    def is_checked(self,*args,**kwargs):
        return is_checked(*args,**kwargs)
    def getbox(self,*args,**kwargs):
        return getbox(*args,**kwargs)
    def connect_clicks(self,ds,robust=True):
      """Connect the different functions"""
      ds2 = dict()
      for d in ds: 
          ds2[d] = get_failsafe(running(ds[d]),robust=robust) 
      for d in ds2:
          bu = getattr(self,d) # label in the interface
          fun = ds2[d] # function to call
          bu.clicked.connect(fun) # connect name to function


def main():
    global form
    form = App()  # We set the form to be our ExampleApp (interface)
    return form


def string2array(v):
    """Convert a string in an array"""
    try:
        v = complex(v) # if it is a number
        v = np.array([v])
        return v
    except:
        v = [complex(iv) for iv in v.split(",")]
        return np.array(v)
    return None


def array2string(v):
    """Convert an array to a string"""
    ss = ""
    ss += str(v[0])
    for i in range(1,len(v)): ss += ","+str(v[i])
    return ss


def get_array(name,v0=[0.,0.,0.],**kwargs):
    """Get an array from a cell"""
    v = getattr(form,name).text() # get the text
    v = string2array(v) # convert to array
    if v is not None: return v # return the array
    else: # something wrong happened
        modify(name,array2string(v0)) # overwrite
        return np.array(v0) # return the default value


def get(name,string=False,default=0.0,call=True):
  """Return a certain value"""
  try:
      obj = getattr(form,name) # get the object
      out = obj.text()
      if string: return out # return as string
      try: # if it is a number
          return float(out) # return as float
      except: # execute
          if call:
              if "import os" in out: raise # silly sanity check
              out = out.replace("\n","")
              a = eval("lambda r: "+out) # execute the string
              # try the function
              try: 
                  a([0.,0.,0.])
                  return a
              except: raise
          else: raise
  except:
      if holler(): print(name,"not found, set to ",default)
      modify(name,default) # set this value
      return default



def getbox(name):
  try:
    obj = getattr(form,name) # get the object
    return str(obj.currentText()) # return the text
  except:
    if holler(): print(name,"not found, set to None")
    return None


def set_combobox(name,cs=[]):
    """Add the different colormaps to a combox"""
    try: cb = getattr(form,name)
    except:
        if holler(): print("Combobox",name,"not found")
        return
    cb.clear() # clear the items
    cb.addItems(cs)



def modify(name,text):
  try:
    obj = getattr(form,name) # get the object
    out = obj.setText(str(text))
    app.processEvents() # update the interface
  except: pass

set_value = modify

def is_checked(name,default=False):
    try:
        obj = getattr(form,name) # get the object
        return obj.isChecked()
    except: return default



def set_image(name,path,width=None,height=None):
  """Set a certain image"""
  label = form.findChild(QtWidgets.QLabel,name) # get the object
  if label is None: 
      print(name,"label not found")
      return
  pixmap = QPixmap(path)
  from PyQt5.QtCore import Qt
  if width and height:
        # Scale to exact size, keeping aspect ratio (optional)
    pixmap = pixmap.scaled(width, height, 
            Qt.KeepAspectRatio, Qt.SmoothTransformation)
  label.setPixmap(pixmap)
  label.show()


def set_logo(name,image,**kwargs):
  """Set a certain logo"""
  qlroot = os.path.dirname(os.path.realpath(__file__))+"/../../"
  path = qlroot+"/interface-pyqt/logos/"+image
  set_image(name,path,**kwargs)
  


def save_interface(self,output=None):
    """Save all the parameter widgets (text fields, comboboxes, checkboxes
    and radio buttons) of the interface to a JSON file"""
    if output is None: output = os.getcwd() + "/QL_save/interface.json"
    out = dict() # dictionary
    for name,obj in inspect.getmembers(self): # all the different objects
        if isinstance(obj,QtWidgets.QLineEdit):
            out[name] = {"type":"line","value":obj.text()}
        elif isinstance(obj,QtWidgets.QComboBox):
            out[name] = {"type":"combo","value":obj.currentText()}
        elif isinstance(obj,(QtWidgets.QCheckBox,QtWidgets.QRadioButton)):
            out[name] = {"type":"check","value":obj.isChecked()}
    with open(output, 'w') as outf: # write as json file
        json.dump(out, outf)


def load_interface(self,inputfile):
    """Restore parameter widgets previously written by save_interface()"""
    with open(inputfile, "r") as inf:
        out = json.load(inf) # dictionary of saved widgets
    for name in out: # loop over saved widgets
        try: obj = getattr(self,name) # get this object
        except AttributeError: continue # widget no longer exists
        entry = out[name]
        try:
            if entry["type"]=="line": obj.setText(entry["value"])
            elif entry["type"]=="combo": obj.setCurrentText(entry["value"])
            elif entry["type"]=="check": obj.setChecked(entry["value"])
        except Exception: pass # widget type changed since the save





def connect_signals(ds):
  for d in ds: # loop over names
    form.connect(self.pb, SIGNAL("clicked()"),self.button_click)



if __name__ == '__main__':  # if we're running file directly and not importing it
    main()  # run the main function



